voltrondata-labs/benchmarks

- benchmarks.json
- benchmarks/_sources.py
- benchmarks/dataset_select_benchmark.py
- benchmarks/tests/test_dataset_select_benchmark.py
- Adds a new dataset, which is just the NYC taxi dataset, except with each month split into 101 parts (because I didn't realize I had an off-by-one until I had written everything already)
- Adds a benchmark which selects a single file from the dataset. Unlike dataset-read, we have a partition filter, and unlike dataset-filter, we aren't filtering the dataset itself, hence, the partition filtering machinery is also benchmarked. This targets the scenario in [ARROW-11781](https://issues.apache.org/jira/browse/ARROW-11781). 
This benchmark should run on S3, once I figure out that part.
> Add dataset-select benchmark

- benchmarks.json
- benchmarks/_sources.py
- benchmarks/csv_read_benchmark.py
- benchmarks/tests/test_csv_read_benchmark.py
Leaving in draft as I'm using pyarrow for the CSV writing but that isn't available on older versions of pyarrow so it would make historical analysis difficult.  We should be able to use pandas for the CSV writing.
> Parameterize the CSV benchmark for compression and streaming

- benchmarks/dataset_read_benchmark.py
- benchmarks/dataset_select_benchmark.py
We did not notice this issue until now because we were running these benchmarks on machines without AWS creds.
`dataset-read` and `dataset-select` benchmarks fail when run on AWS resource (e.g., AWS Lambda) with AWS credentials because conbench is trying to access Ursa’s AWS account public s3 bucket (e.g., ursa-labs-taxi-data-repartitioned-10k) using AWS credentials for VD AWS account.
```
Traceback (most recent call last):
File /var/lang/bin/conbench, line 33, in <module>
sys.exit(load_entry_point('conbench==1.0.0', 'console_scripts', 'conbench')())
File /var/lang/lib/python3.8/site-packages/click/core.py, line 1137, in __call__
return self.main(*args, **kwargs)
File /var/lang/lib/python3.8/site-packages/click/core.py, line 1062, in main
rv = self.invoke(ctx)
File …
```
> Use anonymous=True when connecting to public s3 bucket

- benchmarks/tpch_benchmark.py
"""
The choice type allows a value to be checked against a fixed set of supported values.
All of these values have to be strings.
"""
https://click.palletsprojects.com/en/8.0.x/api/?highlight=click%20choice#click.Choice
> click.Choices may only be strings (no free click type coercion)

- benchmarks/_benchmark.py
- benchmarks/java_micro_benchmarks.py
Java-micro benchmarks started producing more stdout than benchmark machine can load into memory starting with https://github.com/apache/arrow/commit/06fee4545535fc4a1af5c08b4e524ffb89bc7868. This caused benchmark builds running Java benchmarks to fail because `conbench` process running Java-micro benchmarks was killed by OS with exit code 137 (Exit Code 137: Indicates failure as container received SIGKILL (Manual intervention or 'oom-killer' [OUT-OF-MEMORY]).
I decided to handle this issue on benchmarks repo (https://github.com/ursacomputing/benchmarks) side first and then ask Apache Arrow Java community to look into if they can figure out how to reduce amount of stdout for Java-micro benchmarks.
I captured stdout produced by Java-micro benchmarks into a tmp file to see how large it is: …
> Handle large stdout produced by benchmarks

- benchmarks/js_micro_benchmarks.py
JavaScript benchmarks started to output non-json logs in `stderr` in addition to actual results starting with https://github.com/apache/arrow/commit/20b66c255ff617c438775e54081eaa02d5b983e1.
This broke the code that tries to capture benchmark results from stderr.
I will be creating an Apache Arrow story (if it is not already created yet) to log JavaScript benchmark results into a tmp file instead stderr so we can avoid issues like this in the future.
Here is how JavaScript benchmarks stderr looks like since https://github.com/apache/arrow/commit/20b66c255ff617c438775e54081eaa02d5b983e1:
```
(node:1346319) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[
{ …
```
> JavaScript benchmarks > Ignore non-json stderr produced by benchmarks when loading results

- benchmarks.json
- benchmarks/_sources.py
- benchmarks/csv_read_benchmark.py
- benchmarks/tests/test_csv_read_benchmark.py
Take 2. Closes #37 by changing the `CsvReadBenchmark` to inherit from `BenchmarkPythonR` instead of `Benchmark` and adjusting it so it runs [the `read_csv` benchmark from {arrowbench}](https://github.com/ursacomputing/arrowbench/blob/main/R/bm-read-csv.R).
Because the viable cases differ between Python and R (py has streaming, R has dataframe output), the class maintains separate lists of which cases are viable for each language and skips those that aren't. I took this approach because language is not part of case in the parent class. Maybe there's a more elegant alternative?
> [ENG-3649] Add R csv benchmarks

- benchmarks/partitioned_dataset_filter_benchmark.py
- benchmarks/tests/test_cpp_micro_benchmarks.py
- benchmarks/tests/test_csv_benchmark.py
- benchmarks/tests/test_dataframe_to_table_benchmark.py
- benchmarks/tests/test_dataset_filter_benchhmark.py
- benchmarks/tests/test_dataset_read_benchmark.py
- benchmarks/tests/test_dataset_select_benchmark.py
- benchmarks/tests/test_dataset_selectivity_benchmark.py
- benchmarks/tests/test_example_benchmarks.py
- benchmarks/tests/test_file_benchmark.py
- benchmarks/tests/test_java_micro_benchmarks.py
- benchmarks/tests/test_js_micro_benchmarks.py
- benchmarks/tests/test_partitioned_dataset_filter_benchmark.py
- benchmarks/tests/test_tpch_benchmark.py
- benchmarks/tests/test_wide_dataframe_benchmark.py
I broke things with https://github.com/ursacomputing/arrowbench/pull/106 (specifically [here](https://github.com/ursacomputing/arrowbench/pull/106/files#diff-8b62164b35e55affb72f6d95ddc3945e7e8dde444917d3a572858a7ff5537ce6)) by changing a query name from `count_rows` to `dims` (because it checks number of cols in addition to rows). This PR makes the accompanying change in {benchmarks} so it will pass the right argument.
> Hotfix: Renamed query in R dataset benchmark

- benchmarks/_benchmark.py
Closes #107. When it exists, pulls the value for `case_version` out of the tags of the JSON generated by {arrowbench} when running R benchmarks, and appends it to the tags sent on to conbench.
Notably this PR does not replace all the Python-generated tags with the R-generated ones, because they do not correspond exactly, so doing so would break histories. There are reasons they differ, e.g. {arrowbench} does not also append `name` as a `tag` (maybe it should for history's sake? but it's duplicative); params vary in cases like `csv-read` where Python and R do not have the same params and functionality. Long-term, we'll need to fix the situation, but efforts now to align {benchmarks} and {arrowbench} will become historical artifacts as orchestration gets moved out of {benchmarks}, so I …
> Pass through case version tags from R json

- benchmarks/_benchmark.py
- benchmarks/_example_benchmarks.py
- benchmarks/tests/test_example_benchmarks.py
- benchmarks/tests/test_tpch_benchmark.py
- benchmarks/tpch_benchmark.py
Closes #106; parallel to https://github.com/ursacomputing/arrowbench/pull/105. Adds the ability to version cases by overwriting a `version_cases()` method that takes in a case tuple and returns `None` (no versioning; continue current behavior) or an integer, which will be appended to `tags` as `case_version`.
Also adds a pile of type hints to `_benchmark.py` because I wrote them out before when trying to understand data flow.
Also changes the TPC-H benchmark to allow for smaller scale factors and uses them in tests so they don't take half an hour on CI.
> Add Python case versioning capability

- benchmarks/_sources.py
- benchmarks/csv_benchmark.py
- benchmarks/tests/_asserts.py
A PR to [hopefully!] fix the buildkite builds. To assemble this, I installed the nightly version of pyarrow, cleared the data cache temp dir (important!) and then reran everything to see what sizes things came out as.
Beyond file sizes, this makes a couple other small tweaks:
- changes `store_and_fwd_flag` in nyctaxi back to a string, because while it's almost all null, 0, 1, or 2, there's one row with a `*` value that was breaking things
- turned the schemas into functions like {arrowbench}. Not _sure_ this matters (i.e. if the instance was correctly getting bundled with the package or a pointer accidentally getting left behind), but this way is definitely safe.
- set `strings_can_be_null=True` in `pyarrow.csv.ConvertOptions` because this is what pandas does and what pretty much all …
> Fix file size records and schema for all-null cols

- benchmarks/_benchmark.py
- benchmarks/_sources.py
- benchmarks/dataset_filter_benchmark.py
- benchmarks/file_benchmark.py
- benchmarks/tests/_asserts.py
- benchmarks/tests/conftest.py
- benchmarks/tests/test_dataset_filter_benchmark.py
- benchmarks/tests/test_file_benchmark.py
A PR to clean up various issues, mostly with files, causing problems in buildkite builds and tests (especially when run more than once). Specifically:
- Removes file size validation. This was not used in benchmarks themselves, only when loading source data, so this should not affect benchmarks. If we're really worried about file integrity, let's test this some other way that causes fewer headaches.
- Changes cache format to parquet so we can specify more options when writing and reading
- Sets `coerce_timestamps="us"` when writing parquet to fix timestamp precision consistency issues
- Reverts timestamp precision change in asserts because this fixes the issue globally
- Specifies schemas on read, because type inference fails when columns are all null (common in sample data subsets)
- Adds …
> File consistency

- .github/workflows/actions.yml
- benchmarks/_benchmark.py
This PR passes the Arrow PR number to Conbench in the github info dict. This will enable better Conbench history tracking.
> Add pr_number to github_info

- .github/workflows/actions.yml
- benchmarks.json
- benchmarks/_sources.py
- benchmarks/dataset_serialize_benchmark.py
- benchmarks/tests/test_dataset_serialize_benchmark.py
This is work in progress for #123.
> benchmarks: add dataset_serialize_benchmark.py

- benchmarks/cpp_micro_benchmarks.py
Per Elena, the cpp microbenchmarks were sending the wrong hostname, e.g. [this one](https://conbench.ursa.dev/benchmarks/40c3117c1ee141c2b167af3202a6fc8a/) should be a generic AWS name instead of the actual AWS machine name.
This uses `self.conbench.machine_info` attribute for the cpp adapter because that grabs the hostname from the `.conbench` config file, if populated, which is how we're populating `machine_info.name` on some runners.
Long-term, we need to think about how and where we want to store this type of metadata, given we've moved a lot of other things from `.conbench` to env vars. Given I'll need to reconfigure this whole thing anyway to run the adapter directly from arrow-benchmarks-ci, I'm ok with this short-term patch (which is really what most of this file is), as I'll have …
> Use hostname from .conbench config in cpp adapter

- benchmarks/dataset_read_benchmark.py
- benchmarks/dataset_serialize_benchmark.py
The use_async parameter has been removed in https://github.com/apache/arrow/pull/34034
> Remove use_async argument in dataset.to_table call

- benchmarks/tests/test_tpch_benchmark.py
- benchmarks/tpch_benchmark.py
They both frequently have outliers. They should be runable without as many outliers, but given that they do + they contribute to false positives, let's disable them for now and only use the larger scale factors to test these (which are more realistic use cases anyway)
> Remove TPCH 0.01 and 0.1 because they are noisy

- benchmarks/_benchmark.py
This PR addresses https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/121 by overwriting the `publish()` method that most benchmarks use to post benchmark results to Conbench. It now should use the new `benchclients.ConbenchClient`, which has more reasonable retrying logic.
> Use benchclients.ConbenchClient to post benchmarks

- benchmarks/_benchmark.py
#143 caused some builds to start failing because in some cases (archery runs for Java and JavaScript) `optional_benchmark_info` was `None` instead of `{}`, which then causes the result to get rejected by the Conbench API. This changes the defaults for `optional_benchmark_info` so they will always be `{}` if otherwise unpopulated.
Example failed builds:
- JavaScript: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/builds/3103#0188e55e-11a5-4f01-a51b-b505158876e7/6-438
- Java: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-thinkcentre-m75q/builds/3130#0188e55e-157d-46b3-9ab1-8202971e6629/6-5019
> Ensure default for optional_benchmark_info is {}

- benchmarks/_benchmark.py
Closes #145 by posting catastrophic errors instead of just logging them. No tests because we don't have mocks set up for this repo 😢 . 
Uses the `publish()` method directly instead of `record()`, which is different than everything else here, but which is good for moving away from the legacy runner.
> Post catastrophic errors to Conbench

- .github/workflows/actions.yml
- README.md
- benchmarks/_benchmark.py
- benchmarks/_example_benchmarks.py
- benchmarks/cpp_micro_benchmarks.py
- benchmarks/csv_benchmark.py
- benchmarks/dataframe_to_table_benchmark.py
- benchmarks/dataset_filter_benchmark.py
- benchmarks/dataset_read_benchmark.py
- benchmarks/dataset_select_benchmark.py
- benchmarks/dataset_selectivity_benchmark.py
- benchmarks/dataset_serialize_benchmark.py
- benchmarks/file_benchmark.py
- benchmarks/filesystem_benchmark.py
- benchmarks/java_micro_benchmarks.py
- benchmarks/js_micro_benchmarks.py
- benchmarks/partitioned_dataset_filter_benchmark.py
- benchmarks/tests/test_tpch_benchmark.py
- benchmarks/tpch_benchmark.py
- benchmarks/wide_dataframe_benchmark.py
- requirements-dev.txt
- requirements.txt
As part of https://github.com/conbench/conbench/issues/1439, move from installing `conbench` as a package to the new, much lighter `conbenchlegacy` that only includes the bits needed (the CLI and the runner), not the entire webapp.
Cleans up some dep specification along the way, but is mostly just changing imports.
> Switch to conbenchlegacy package

- benchmarks/cpp_micro_benchmarks.py
Fixes https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/163.
> supply github info through environment

- benchmarks/dataset_serialize_benchmark.py
Fixes https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/166.
This PR sets `pre_buffer=False` when reading files in the `dataset-serialize` benchmark in order to avoid https://github.com/apache/arrow/issues/38438. 
Once that's fixed, we can probably come back and remove this.
> Fix dataset-serialize benchmark by setting pre_buffer=False

- benchmarks/js_micro_benchmarks.py
In the process of fixing JS benchmarks I noticed the parsing of the results wasn't working: https://github.com/apache/arrow/pull/37668#issuecomment-1781790381.
Something may have changed in `yarn` since the last time we ran these? not sure
> Fix JS parsing

- README.md
I have corrected the links that were causing a '404 Not Found' by updating the path and filename.
> doc(README.md): Fix the wrong path

- benchmarks/dataset_serialize_benchmark.py
This reverts commit d412d2faf175a1891bc69059444c5174f48b1ff8.
This benchmark was fixed in https://github.com/apache/arrow/pull/38466.
> Revert "Fix dataset-serialize benchmark by setting pre_buffer=False (#152)"

- benchmarks/tests/test_wide_dataframe_benchmark.py
- benchmarks/wide_dataframe_benchmark.py
See https://github.com/apache/arrow/pull/39112
> Stop running `use_legacy_dataset=true` for wide-benchmark

- benchmarks.json
- benchmarks/cpp_micro_benchmarks.py
- benchmarks/tests/test_cpp_micro_benchmarks.py
This PR tells Archery to run each cpp microbenchmark executable with the instruction to do ~20~ 6 reps, where each rep runs as many iterations as it can in 0.05 seconds (or a bit more if it's statistically necessary). This should smooth out the data since we now alert on the "best rep" instead of the mean, resulting in fewer false positives and less outlier weight.
> Bump cpp-micro repetitions to 6

- benchmarks/cpp_micro_benchmarks.py
- benchmarks/tests/test_cpp_micro_benchmarks.py
- requirements.txt
Pairs well with https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/181 and https://github.com/apache/arrow/pull/40925.
This PR allows us to use the pre-built arrow for C++ benchmarks by passing its path through the env var. This also allows us to run more benchmark suites since the pre-built arrow has more stuff in it.
> Use pre-built arrow for cpp benchmarks by default
